# Generated by Django 6.0.4 on 2026-05-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_step', models.IntegerField()),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('network_io', models.FloatField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('z_score_flag', models.BooleanField(default=False)),
                ('iforest_flag', models.BooleanField(default=False)),
                ('pattern', models.CharField(default='combined', max_length=32)),
                ('scheduler_type', models.CharField(default='predictive', max_length=20)),
            ],
            options={
                'ordering': ['-created_at', 'time_step'],
            },
        ),
    ]
