# Generated by Django 6.0.4 on 2026-04-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduler_type', models.CharField(max_length=20)),
                ('pattern', models.CharField(max_length=20)),
                ('steps', models.IntegerField()),
                ('overload_events', models.IntegerField()),
                ('overload_rate', models.FloatField()),
                ('avg_cpu', models.FloatField()),
                ('avg_capacity', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('scale_up_count', models.IntegerField(default=0)),
                ('scale_down_count', models.IntegerField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('scheduler_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_record', to='scheduler.schedulerrun')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
