# Generated by Django 6.0.4 on 2026-04-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduler_type', models.CharField(choices=[('reactive', 'Reactive'), ('predictive', 'Predictive')], max_length=20)),
                ('pattern', models.CharField(default='combined', max_length=20)),
                ('steps', models.IntegerField(default=200)),
                ('seed', models.IntegerField(default=42)),
                ('overload_events', models.IntegerField(default=0)),
                ('overload_rate', models.FloatField(default=0.0)),
                ('avg_cpu', models.FloatField(default=0.0)),
                ('avg_capacity', models.FloatField(default=0.0)),
                ('total_cost', models.FloatField(default=0.0)),
                ('scale_up_count', models.IntegerField(default=0)),
                ('scale_down_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workload_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduler_runs', to='simulation.workloadrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchedulerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_step', models.IntegerField()),
                ('workload', models.FloatField()),
                ('capacity', models.IntegerField()),
                ('cpu_usage', models.FloatField()),
                ('overloaded', models.BooleanField(default=False)),
                ('action', models.CharField(choices=[('scale_up', 'Scale Up'), ('scale_down', 'Scale Down'), ('hold', 'Hold')], default='hold', max_length=15)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='scheduler.schedulerrun')),
            ],
            options={
                'ordering': ['time_step'],
            },
        ),
    ]
