# Generated by Django 6.0.4 on 2026-05-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleraction',
            name='memory_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scheduleraction',
            name='network_io',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='scheduleraction',
            name='trigger_resource',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='schedulerrun',
            name='avg_memory',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='schedulerrun',
            name='avg_network',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='schedulerrun',
            name='overload_cpu_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedulerrun',
            name='overload_memory_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedulerrun',
            name='overload_network_count',
            field=models.IntegerField(default=0),
        ),
    ]
