# Generated by Django 6.0.4 on 2026-04-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelComparisonResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series_length', models.IntegerField(default=0)),
                ('pattern', models.CharField(default='combined', max_length=32)),
                ('seed', models.IntegerField(default=42)),
                ('gbr_rmse', models.FloatField(blank=True, null=True)),
                ('gbr_mae', models.FloatField(blank=True, null=True)),
                ('gbr_r2', models.FloatField(blank=True, null=True)),
                ('lstm_rmse', models.FloatField(blank=True, null=True)),
                ('lstm_mae', models.FloatField(blank=True, null=True)),
                ('lstm_r2', models.FloatField(blank=True, null=True)),
                ('arima_rmse', models.FloatField(blank=True, null=True)),
                ('arima_mae', models.FloatField(blank=True, null=True)),
                ('arima_r2', models.FloatField(blank=True, null=True)),
                ('combined_rmse', models.FloatField(blank=True, null=True)),
                ('combined_mae', models.FloatField(blank=True, null=True)),
                ('combined_r2', models.FloatField(blank=True, null=True)),
                ('best_model', models.CharField(default='', max_length=32)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='modeltrainingrun',
            name='extra_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='modeltrainingrun',
            name='error_msg',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='modeltrainingrun',
            name='model_type',
            field=models.CharField(choices=[('gbr', 'GradientBoosting'), ('lstm', 'LSTM (PyTorch)'), ('arima', 'ARIMA'), ('combined', 'Combined LSTM+ARIMA')], max_length=32),
        ),
        migrations.AlterField(
            model_name='modeltrainingrun',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16),
        ),
    ]
