# Generated by Django 6.0.5 on 2026-05-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_model', '0002_modelcomparisonresult_modeltrainingrun_extra_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticalValidationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('n_runs', models.IntegerField(default=20)),
                ('pattern', models.CharField(default='combined', max_length=32)),
                ('steps', models.IntegerField(default=300)),
                ('elapsed_seconds', models.FloatField(blank=True, null=True)),
                ('lstm_win_rate', models.FloatField(blank=True, null=True)),
                ('lstm_mean_r2', models.FloatField(blank=True, null=True)),
                ('lstm_std_r2', models.FloatField(blank=True, null=True)),
                ('gbr_mean_r2', models.FloatField(blank=True, null=True)),
                ('arima_mean_r2', models.FloatField(blank=True, null=True)),
                ('combined_mean_r2', models.FloatField(blank=True, null=True)),
                ('full_results', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
