# Generated by Django 6.0.4 on 2026-04-14 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(choices=[('gradual', 'Gradual'), ('spike', 'Spike'), ('periodic', 'Periodic'), ('combined', 'Combined')], default='combined', max_length=20)),
                ('steps', models.IntegerField(default=200)),
                ('seed', models.IntegerField(default=42)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkloadDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_step', models.IntegerField()),
                ('workload', models.FloatField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='simulation.workloadrun')),
            ],
            options={
                'ordering': ['time_step'],
            },
        ),
    ]
