# Generated by Django 6.0.4 on 2026-05-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloaddatapoint',
            name='memory_usage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='workloaddatapoint',
            name='network_io',
            field=models.FloatField(default=0.0),
        ),
    ]
